alias aply="ansible-playbook"
alias d="docker"
alias dimg="docker image"
alias dimgs="docker images"
alias dimgrm="docker image rm -f"
alias dcon="docker container"
alias dconls="docker container ls"
alias dconrm="docker container rm -f"
